### ISSUE TITLE
你好，windows下加载你的sln出错

### ISSUE THREAD

**Issue by shaoming20798** [senlinuc/caffe_ocr#1]
senlinuc,你好
    我clone下来你的代码，用vs15打开sln，显示caffe.vcxproj加载错误，暂时没有找到原因，请问你那里工程师可以正常打开的吗

**Comment by senlinuc** [comment]
需要先安装cuda，我用的是8.0

**Comment by shaoming20798** [comment]
你好，再次尝试了下。我在linux上编译运行你的代码，发现几个问题。
1.caffe.proto里没有WarpCTCLossParameter，这个我自己手动添加了下，不知道是否有问题，只有1个参数blank_index；
2.我在尝试你的densenet-no-blstm_train-val.prototxt里的网络的方法（我这里修改了你的data层，使用的是hdf5格式，而不是你原本的data格式），无法训练，原因出在了Reshape这一层，Reshape后经过fc1x，再送给ctcloss会出错，维度不匹配，看了下日志维度确实不匹配。
主要是第2个问题，你那里训练是可以的吗

**Comment by senlinuc** [comment]
1. 是CTCLossParameter
2. 发下你的日志看下shape是怎么变化的

**Comment by shaoming20798** [comment]
1.如果是CTCLossParameter的话，有另外1个问题，就是你的ctc_loss_layer需要的是3个输入data_blob，seq_ind_blob和target_seq_blob，但是你的prototxt里面只配置了两个bottom，还少1个。
2.我在单位，不能上传数据到外部，哈哈。。。可以留个微信或者QQ什么的吗，可以把错误信息发你看下

**Comment by senlinuc** [comment]
ctcloss用的是warp_ctc_loss_layer.cpp，不是ctc_loss_layer.cpp，有点乱，稍后我会整理下

**Comment by shaoming20798** [comment]
好的，谢谢

**Comment by apple1987** [comment]
我新安装的VS2015 也是打开报错：affe\caffe.vcxproj : error  : 发生一个或多个错误。不知道是什么原因导致的，cuda8.0版本

**Comment by rickerliang** [comment]
是不是在readme里面说明一下vs2015的版本，因为express版是打不开的，工程里面用到了extension，应该是cuda的原因😄😄
