### ISSUE TITLE
3rdparty好像还要补充libjpeg和libpng，boost的版本貌似要使用1.57

### ISSUE THREAD

**Issue by rickerliang** [senlinuc/caffe_ocr#11]
boost的版本要1.57，好像是3rdparty里面leveldb要链接1.57的lib，但boost 1.57在sourceforge没有vc2015的二进制，还需要自己编一下

**Comment by apple1987** [comment]
我之前下载其他版本也是提示缺少1.57的库文件，不过我用动态链接库的opencv 不用libjpeg，libpng，静态编译的库里面自带了这2个库。

**Comment by senlinuc** [comment]
boost 1.57已经上传到 http://pan.baidu.com/s/1kV7U7Fx
libjpeg, libpng用opencv里的就行

**Comment by rickerliang** [comment]
ok，谢谢😁😁

**Comment by rickerliang** [comment]
ok，谢谢😁😁

**Comment by yiran-THU** [comment]
@senlinuc 
能否麻烦您将编译好的，带libjpeg和libpng的OPENCV 2也传到网盘，谢谢
