### ISSUE TITLE
DenseBlockLayer的 openblas实现

### ISSUE THREAD

**Issue by sunjunlishi** [senlinuc/caffe_ocr#110]
template <typename Dtype>
	void convolution_Fwd(Blob<Dtype>* input, Blob<Dtype>* output, Blob<Dtype>* filter, int N, int c_output, int c_input, int h_img, int w_img, int h_filter, int w_filter) {
		int outputShape[] = { N,c_output,h_img,w_img };
		vector<int> outputShapeVec(outputShape, outputShape + 4);
		output->Reshape(outputShapeVec);

		vector<int > outShap = output->shape();
		std::string info="";
		for (int k = 0; k < outShap.size(); ++k)
		{
			char szBuf[256];
			sprintf(szBuf," %d", outShap[k]);
			info += szBuf;
		}

		info += "| ";
		outShap = filter->shape();
		for (int k = 0; k < outShap.size(); ++k)
		{
			char szBuf[256];
			sprintf(szBuf, " %d", outShap[k]);
			info += szBuf;
		}

		info += "| ";
		outShap = input->shape();
		for (int k = 0; k < outShap.size(); ++k)
		{
			char szBuf[256];
			sprintf(szBuf, " %d", outShap[k]);
			info += szBuf;
		}
		 Dtype * outputPtr = output->mutable_cpu_data();
		const Dtype * col_buff = input->cpu_data();
		const Dtype * weights = filter->cpu_data();
		
		caffe_cpu_gemm<Dtype>(CblasNoTrans, CblasNoTrans, c_output,
			h_img*w_img, c_input*h_filter*w_filter,
			(Dtype)1., weights, col_buff,
			(Dtype)0., outputPtr );
	}

**Comment by sunjunlishi** [comment]
我像如此实现，我打印出
out 1 8 16  260 
filter 8 64 3 3
input 1 64 16 260 发现 input 不对，少了3*3； 我们应该 怎么实现啊；
还有训练参数文件，从哪来呀；

**Comment by sunjunlishi** [comment]
你好 还有 ；
DenseBlockLayer总是在这 崩溃呀；为啥
		this->merged_conv[0]->CopyFrom(*(bottom[0]));

**Comment by sunjunlishi** [comment]
你的 这个 项目 非常 不错，有 lstm 对后续的 其他项目比如语音等都是有非常大的好处。而且你的项目非常完整。我已经 训练了你的另外一个模型，效果还可以。

**Comment by sunjunlishi** [comment]
大拿，怎么cpu版本，不可以呀；求救啊；

**Comment by sunjunlishi** [comment]
你好我不用 memory-efficient densenet，应该怎样搞个网络呀；

**Comment by mengpengfei** [comment]
> 大拿，怎么cpu版本，不可以呀；求救啊；cpu版本应该好好搞搞呀。

cpu 版本 gpu版本我都有，这个项目在图片大小方便很多问题，

**Comment by mengpengfei** [comment]
> 终于明白了，memory-efficient densenet也是原班人马搞的，但是没有优化速度，好可惜。
> （你好我不用 memory-efficient densenet，应该怎样搞个网络呀；）

我已经把ocr_test里的函数编译成dll，很方便调用

**Comment by sunjunlishi** [comment]
cpu的 densenet 你优化了吗；编译dll很简单。

**Comment by sunjunlishi** [comment]
@mengpengfei cpu版本很慢，denseBlockLayer你优化了？能共享下这个文件便可。

**Comment by sunjunlishi** [comment]
@mengpengfei  DenseBlockLayer的 openblas实现 你实现了？？

**Comment by sunjunlishi** [comment]
作者，你可以用普通的densenet实现啊；这样更好的用cpu，更好的用到项目上，会产生很大影响。

**Comment by sunjunlishi** [comment]
作者，你的模型怎么改成 普通的 densenet网络呀；我改了，不中啊；望指教啊；

**Comment by sunjunlishi** [comment]
densenet 相关，我训练的时候，总是进行不了。

**Comment by sunjunlishi** [comment]
我正在 尝试 普通的 densenet可以训练，效果总是训练不太好。
作者大拿希望你能够 搞个 普通的 densenet 网络啊；这样的应用更加广泛呀；

**Comment by sunjunlishi** [comment]
基本可以尝试普通的 densenet.作者的 一个 densenet是8个 contact。每个 contact里面有个 1*1 和 3*3 的卷积，还有 bn。。。。ok
