### ISSUE TITLE
从词典随机生成数据训练不收敛

### ISSUE THREAD

**Issue by wenlive** [senlinuc/caffe_ocr#117]
统计发现现有训练数据字符分布不均衡严重，CTC的假设不是有字符前后独立分布么，为什么按均匀分布随机生成的数据反而难以收敛。生成的数据映射关系没变，大小相同，类别仍5990种，总量600w张。

**Comment by wenlive** [comment]
ctc_loss从200降到80多久不变了，用了warmup训练可以降到6-8左右，但仍不收敛。
如没有这种现象，可以分享下训练参数设置么

**Comment by Ryansanity** [comment]
您好 我也遇到了训练不收敛的问题 请问您后来怎么解决问题的？
