### ISSUE TITLE
您好，我配置标签时这样的

### ISSUE THREAD

**Issue by Mmmoran** [senlinuc/caffe_ocr#118]
我的图片是横着的10个字长度的jpg文件，标签得txt应该是文件名字+10个标签吗？
所用图片里只用到了90个字符，训练时全连接层的输出91维度（90个字符+blank）吗？还是只90个就行了

**Comment by chensiyuanlove** [comment]
是的，全连接层需要的是 91个字符，但是“无意义字符”一般开源代码都会在代码中加，而不会加在你标签变量中。所以你的标签变量是90个字符。你可以看看你的代码，在代码train.py里面搜  《你的标签变量名》然后一步步往下面跟，就能看到 代码会在你标签末尾加多一个  “无意义字符”
