### ISSUE TITLE
Multilabel

### ISSUE THREAD

**Issue by Simon-Duan** [senlinuc/caffe_ocr#14]
你好，修改代码支持mulitilabel的时候按照你发的链接就可以么？因为我发现你的代码跟这个链接的还不太一样.

**Comment by senlinuc** [comment]
我的代码里面是修改好的，直接用就行，好像链接里某些地方有bug.

**Comment by Simon-Duan** [comment]
@senlinuc  我是在linux下搞的，，，没搞通，幸好找到一个已经改好的哈哈～[擦发反而-multilabel](https://github.com/last-one/caffe-multilabel)

另外问一下，你代码里的ctcpp_entrypoint.cpp/.cu是做什么用的呢？我把wrap_ctc__loss层加进去编译通过，再加这个的话就一大堆错误
