### ISSUE TITLE
测试densenet系列的模型，DenseBlock_layer.cu:231行总报错，提示 CUDNN_STATUS_NOT_INITIALIZED，不清楚原因。

### ISSUE THREAD

**Issue by hbulaoma** [senlinuc/caffe_ocr#17]

**Comment by senlinuc** [comment]
你用的是最新的代码吗？这两天DenseBlock_layer.cu我改了个batch size有变化时出错的bug。

**Comment by hbulaoma** [comment]
昨天晚上更新了最新的代码，仍然报错。inception-bn-res-blsm和resnet-res-blstm两套模型一直可以使用。不知道是显卡版本(GTX1080)的原因，还是代码造成的。

**Comment by yaokeepmoving** [comment]
最好将完整的报错信息粘贴或是截图出来，方便分析

**Comment by hbulaoma** [comment]
可以贴图吗？报错如下：
F1113 20:15:52.651626 13012 DenseBlock_layer.cu:231] Check failed: status == CUDNN_STATUS_SUCCESS(1 vs. 0) CUDNN_STATUS_NOT_INITIZLIZED

**Comment by senlinuc** [comment]
是不是cudnn版本的问题？我的是7.0

**Comment by prfans** [comment]
这个可能是显卡驱动的问题,我是把cudnn7.0改为5.0解决的.
