### ISSUE TITLE
可否共享训练好的模型

### ISSUE THREAD

**Issue by 10183308** [senlinuc/caffe_ocr#2]
能否分享你已经训练好的模型？
谢谢

**Comment by senlinuc** [comment]
可以，稍后我会把下载地址放到README中

**Comment by ZhangXinNan** [comment]
@senlinuc 
合成的中文数据（http://pan.baidu.com/s/1c2fHpvE） 我看了下这个是压缩文件8.6G，能不能解压后上传到云盘？

**Comment by senlinuc** [comment]
下载失败可能跟你的网络有关，我这是正常的。
