### ISSUE TITLE
请问一下，在linux环境下，是把相关修改合并到哪一版本的caffe之中呢？caffe-warp-ctc 还是caffe-lstm？谢谢

### ISSUE THREAD

**Issue by wenlihaoyu** [senlinuc/caffe_ocr#3]

**Comment by senlinuc** [comment]
合到master就可以，我的caffe改的比较乱，比较接近的可能是https://github.com/BVLC/caffe/releases/tag/rc5吧

**Comment by zjuDebug** [comment]
@senlinuc ，你好，想问下如何merge代码，我用如下命令进行merge会产生冲突：
cd caffe-rc5/
git remote add caffe_ocr https://github.com/senlinuc/caffe_ocr.git
git fetch caffe_ocr
git merge caffe_ocr/master

冲突如下：
“”“
Auto-merging examples/cpp_classification/readme.md
CONFLICT (add/add): Merge conflict in examples/cpp_classification/readme.md
Auto-merging examples/cifar10/train_quick.sh
CONFLICT (add/add): Merge conflict in examples/cifar10/train_quick.sh
Auto-merging examples/cifar10/train_full_sigmoid_bn.sh
CONFLICT (add/add): Merge conflict in examples/cifar10/train_full_sigmoid_bn.sh
Auto-merging examples/cifar10/train_full_sigmoid.sh
CONFLICT (add/add): Merge conflict in examples/cifar10/train_full_sigmoid.sh
Auto-merging examples/cifar10/train_full.sh
CONFLICT (add/add): Merge conflict in examples/cifar10/train_full.sh
Auto-merging examples/cifar10/create_cifar10.sh
CONFLICT (add/add): Merge conflict in examples/cifar10/create_cifar10.sh
Auto-merging examples/cifar10/cifar10_full_sigmoid_solver_bn.prototxt
CONFLICT (add/add): Merge conflict in examples/cifar10/cifar10_full_sigmoid_solver_bn.prototxt
Auto-merging examples/cifar10/cifar10_full_sigmoid_solver.prototxt
CONFLICT (add/add): Merge conflict in examples/cifar10/cifar10_full_sigmoid_solver.prototxt
Auto-merging examples/CMakeLists.txt
CONFLICT (add/add): Merge conflict in examples/CMakeLists.txt
Auto-merging examples/02-fine-tuning.ipynb
CONFLICT (add/add): Merge conflict in examples/02-fine-tuning.ipynb
Auto-merging README.md
CONFLICT (add/add): Merge conflict in README.md“””
谢谢
