### ISSUE TITLE
是否ctc对连续数字的识别率不够高？

### ISSUE THREAD

**Issue by ares89** [senlinuc/caffe_ocr#67]
我尝试使用模型识别包含 000.000
666，66
0.8888
5000，000，00等数字的图片
最终都没有能正确识别
总是丢失字符
请问有没有遇到同样问题的？

**Comment by piaobuliao** [comment]
对于连续的相同数字CTC是容易漏，考虑多增加些这种样本

**Comment by ares89** [comment]
找到原因了，要对图片进行拉伸
