### ISSUE TITLE
训练疑问，迭代两万次之后loss卡在30不降低了

### ISSUE THREAD

**Issue by Levi-zhan** [senlinuc/caffe_ocr#72]
你好，我们做身份证识别，用你的代码训过，很正常，但是精度还不够高。于是就又生成了200W张身份证地址的图片加到你的训练样本里面一起训，对应的label也加进去了，然后把你原本的字典扩充了一下，加入了一些地址的生僻字，这样差不多就有500W张，经过一些调参，但是迭代两万次之后loss就一直卡在30左右不下降了，我们的样本和label应该是可以对的上的，没错。但是loss就是不降，请问你有什么建议呢？

**Comment by af258963** [comment]
@Levi-zhan 我的也是一直在26，下降不下去

**Comment by shaoshuaiche** [comment]
这个解决了吗

**Comment by shaoshuaiche** [comment]
我的ctc-loss 一直在50左右，50000步了

**Comment by Levi-zhan** [comment]
解决了，谢谢。我保证每个图片里面字符个数统一就行了，比如每张图10个子符，没有就补充数字。虽然不知道为什么会这样。你有什么想法或者意见么？


 
---原始邮件---
发件人: "shaoshuaiche"<notifications@github.com>
发送时间: 2019年4月22日(星期一) 晚上10:16
收件人: "senlinuc/caffe_ocr"<caffe_ocr@noreply.github.com>;
抄送: "Mention"<mention@noreply.github.com>;"Levi-zhan"<1799533198@qq.com>;
主题: Re: [senlinuc/caffe_ocr] 训练疑问，迭代两万次之后loss卡在30不降低了 (#72)



这个解决了吗

**Comment by mengpengfei** [comment]
加qq讨论下 3455473568

**Comment by sunjunlishi** [comment]
@Levi-zhan 你好，你搞身份证的，有好的模型吗，有酬劳，联系下你

**Comment by sunjunlishi** [comment]
@senlinuc 你好作者，你有更好的模型吗？或者身份证识别的，更好。大酬劳奉上啊。
