### ISSUE TITLE
使用ImageData层和LMDB方式读取数据有区别吗？

### ISSUE THREAD

**Issue by saintscript** [senlinuc/caffe_ocr#74]
在imageData层指定训练数据的image folder和.txt文件的位置，也可以训练，这种方式和使用data层传入转换好的lmdb文件有什么区别么？

**Comment by senlinuc** [comment]
没啥区别，主要是数据量太大，转成lmdb太慢了，把图片放到ssd上，直接用图片训练io速度也还可以，而且灵活很多，特别是数据集变动比较多里。
